baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Test site for mod-katex'

[module]
  # Build and serve using local mod-katex clone declared in the named Hugo workspace:
  workspace = "mod-katex.work"
  [[module.imports]]
    path = "github.com/oolonek/mod-katex"
  [[module.imports.mounts]]
    source = "dist"
    target = "static"
  [[module.imports.mounts]]
    source = "layouts"
    target = "layouts"